export enum EducationLevel {
  ELEMENTARY = 'ELEMENTARY',
  HIGH_SCHOOL = 'HIGH_SCHOOL',
  UNDERGRADUATE = 'UNDERGRADUATE',
  POSTGRADUATE = 'POSTGRADUATE',
  MASTER = 'MASTER',
  DOCTORATE = 'DOCTORATE',
}
