export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const PASSWORD_HASHER = Symbol('PASSWORD_HASHER');
export const MAILER_SERVICE = Symbol('MAILER_SERVICE');
export const DRIZZLE_DB = Symbol('DRIZZLE_DB');
export const AUTH_SERVICE = Symbol('AUTH_SERVICE');
export const PASSWORD_RESET_SERVICE = Symbol('PASSWORD_RESET_SERVICE');
export const GOOGLE_CONFIG_SERVICE = Symbol('GOOGLE_CONFIG_SERVICE');
export const COURSE_REPOSITORY = Symbol('COURSE_REPOSITORY');
export const SUB_COURSE_REPOSITORY = Symbol('SUB_COURSE_REPOSITORY');
export const MODULE_REPOSITORY = Symbol('MODULE_REPOSITORY');
export const VIDEO_REPOSITORY = Symbol('VIDEO_REPOSITORY');
export const VIDEO_PROGRESS_REPOSITORY = Symbol('VIDEO_PROGRESS_REPOSITORY');
export const NOTIFICATION_SERVICE = Symbol('NOTIFICATION_SERVICE');
export const OFFENSIVE_REPOSITORY = Symbol('OFFENSIVE_REPOSITORY');
export const OFFENSIVE_SERVICE = Symbol('OFFENSIVE_SERVICE');
export const COMMUNITY_REPOSITORY = Symbol('COMMUNITY_REPOSITORY');
export const COMMUNITY_MEMBER_REPOSITORY = Symbol(
  'COMMUNITY_MEMBER_REPOSITORY',
);
export const COMMUNITY_INVITE_REPOSITORY = Symbol(
  'COMMUNITY_INVITE_REPOSITORY',
);
export const FRIEND_REQUEST_REPOSITORY = Symbol('FRIEND_REQUEST_REPOSITORY');
export const FRIENDSHIP_REPOSITORY = Symbol('FRIENDSHIP_REPOSITORY');
export const BLOCK_REPOSITORY = Symbol('BLOCK_REPOSITORY');
export const NOTIFICATION_REPOSITORY = Symbol('NOTIFICATION_REPOSITORY');
export const MESSAGE_REPOSITORY = Symbol('MESSAGE_REPOSITORY');
export const PINNED_MESSAGE_REPOSITORY = Symbol('PINNED_MESSAGE_REPOSITORY');
export const REDIS_SERVICE = Symbol('REDIS_SERVICE');
export const RABBITMQ_SERVICE = Symbol('RABBITMQ_SERVICE');
export const PUSH_NOTIFICATION_SERVICE = Symbol('PUSH_NOTIFICATION_SERVICE');
export const PUSH_SUBSCRIPTION_REPOSITORY = Symbol(
  'PUSH_SUBSCRIPTION_REPOSITORY',
);
export const COMMUNITY_MESSAGE_REPOSITORY = Symbol(
  'COMMUNITY_MESSAGE_REPOSITORY',
);
export const PINNED_COMMUNITY_MESSAGE_REPOSITORY = Symbol(
  'PINNED_COMMUNITY_MESSAGE_REPOSITORY',
);
export const MESSAGE_ATTACHMENT_REPOSITORY = Symbol(
  'MESSAGE_ATTACHMENT_REPOSITORY',
);
export const COMMUNITY_MESSAGE_ATTACHMENT_REPOSITORY = Symbol(
  'COMMUNITY_MESSAGE_ATTACHMENT_REPOSITORY',
);
export const MIND_MAP_REPOSITORY = Symbol('MIND_MAP_REPOSITORY');
export const CALL_ROOM_REPOSITORY = Symbol('CALL_ROOM_REPOSITORY');
export const QUIZ_SESSION_REPOSITORY = Symbol('QUIZ_SESSION_REPOSITORY');
export const QUIZ_QUESTION_REPOSITORY = Symbol('QUIZ_QUESTION_REPOSITORY');
export const QUIZ_OPTION_REPOSITORY = Symbol('QUIZ_OPTION_REPOSITORY');
export const QUIZ_ANSWER_REPOSITORY = Symbol('QUIZ_ANSWER_REPOSITORY');
export const SUBSCRIPTION_REPOSITORY = Symbol('SUBSCRIPTION_REPOSITORY');
export const REGISTRATION_TOKEN_REPOSITORY = Symbol(
  'REGISTRATION_TOKEN_REPOSITORY',
);
export const FISCAL_INFO_REPOSITORY = Symbol('FISCAL_INFO_REPOSITORY');
export const INVOICE_REPOSITORY = Symbol('INVOICE_REPOSITORY');
export const AUTO_INVOICE_CONFIG_REPOSITORY = Symbol(
  'AUTO_INVOICE_CONFIG_REPOSITORY',
);

